  Page({
    data:{
      student:[
      {
        location:"00001:",
        name:"Sage",
        ming:"圣祈",
        id:"中国",
        skill:"医疗，生命科学",
        tel:"1222222",
        imagepath:"https://i.imgtg.com/2022/10/08/pEaEr.jpg",
      },
      {
        location:"00002:",
        name:"Chamber",
        ming:"钱博尔",
        id:"法国",
        skill:"金融，证券市场",
        tel:"1333333",
        imagepath:"https://i.imgtg.com/2022/10/08/pEoIM.jpg",
      },
      {
        location:"00003:",
        name:"Neon",
        ming:"泽丽",
        id:"菲律宾",
        skill:"电力，充电续航",
        tel:"1444444",
        imagepath:"https://i.imgtg.com/2022/10/08/pE5FG.jpg",
      },
      {
        location:"00004:",
        name:"Skye",
        ming:"丝凯",
        id:"澳大利亚",
        skill:"生物，自然科学",
        tel:"1555555",
        imagepath:"https://i.imgtg.com/2022/10/11/p3TvY.jpg",
      },
      {
        location:"00005:",
        name:"Sova",
        ming:"蘇法",
        id:"俄罗斯",
        skill:"信息，无人机方向",
        tel:"1666666",
        imagepath:"https://i.imgtg.com/2022/10/08/pEWUD.jpg",
      },
      {
        location:"00006:",
        name:"Jett",
        ming:"捷缇",
        id:"韩国",
        skill:"风力，气雾自然",
        tel:"1777777",
        imagepath:"https://i.imgtg.com/2022/10/08/pET9I.jpg",
      },
      {
        location:"00007:",
        name:"Raze",
        ming:"芮兹",
        id:"巴西",
        skill:"导弹，装备研发",
        tel:"1888888",
        imagepath:"https://i.imgtg.com/2022/10/08/pEYWI.jpg",
      }
      ,
      {
        location:"00008:",
        name:"Astra",
        ming:"亚星卓",
        id:"非洲迦纳",
        skill:"星象，天文观测",
        tel:"1999999",
        imagepath:"https://i.imgtg.com/2022/10/11/p3Udv.jpg",
      }
      ]},
      f1:function(event){
        var id_1=event.currentTarget.dataset.id_1
        var id_2=event.currentTarget.dataset.id_2
        var id_3=event.currentTarget.dataset.id_3
        var id_4=event.currentTarget.dataset.id_4
        var id_5=event.currentTarget.dataset.id_5
        wx.navigateTo({
          url: "/endl/endl?id_1=" +id_1+"&id_2=" + id_2+"&id_3=" + id_3+"&id_4=" + id_4+"&id_5=" + id_5,
        })
      }
  })